[package]
name = "svx-cli"
description = "The svx command-line tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "svx"
path = "src/main.rs"

[dependencies]
svx-core = { path = "../svx-core" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
humantime = "2"
serde_json = "1"
tempfile = "3"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
serde_json = "1"
tempfile = "3"

[lints]
workspace = true
