//! Managed Mode key release (see `spec/crypto-profile.md` §12).
//!
//! When the managed service or the recipient key agent releases a share, it
//! re-seals it with HPKE to a fresh X25519 key generated by the client for
//! this one request. TLS-terminating intermediaries therefore never see a
//! share, and a captured response is useless without the client's ephemeral
//! secret key.
//!
//! ```text
//! info = "SVX-1 release\0" ‖ role ‖ artifact_id ‖ txn ‖ key_id(e_pk)
//! (enc, ct) = HPKE.SealBase(e_pk, info, aad = "", share)
//! ```
//!
//! The client also binds `e_pk` and `txn` into its OIDC login through the
//! `nonce` parameter, so an ID token can only ever be used to release shares
//! to the key pair that requested it:
//!
//! ```text
//! nonce = hex(SHA-256("SVX-1 oidc\0" ‖ e_pk ‖ txn))
//! ```

use hpke::{Deserializable, OpModeR, OpModeS, Serializable};
use sha2::{Digest, Sha256};
use svx_format::EnvelopeRole;

use crate::SEALED_SHARE_LEN;
use crate::error::{CryptoError, Result};
use crate::keys::{HpkeKem, KemPublicKey, KemSecretKey};
use crate::schedule::Share;

type HpkeAead = hpke::aead::ChaCha20Poly1305;
type HpkeKdf = hpke::kdf::HkdfSha256;

/// Length of a release transaction identifier.
pub const TXN_LEN: usize = 16;

fn info(
    role: EnvelopeRole,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    client: &KemPublicKey,
) -> Vec<u8> {
    let mut v = Vec::with_capacity(15 + 1 + 16 + 16 + 16);
    v.extend_from_slice(b"SVX-1 release\0");
    v.push(role.to_byte());
    v.extend_from_slice(artifact_id);
    v.extend_from_slice(txn);
    v.extend_from_slice(&client.key_id());
    v
}

/// Re-seal a released share to the client's ephemeral public key.
pub fn seal_released_share(
    role: EnvelopeRole,
    share: &Share,
    client: &KemPublicKey,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    rng: &mut impl rand_core::CryptoRng,
) -> Result<([u8; 32], Vec<u8>)> {
    let (enc, ct) = hpke::single_shot_seal_with_rng::<HpkeAead, HpkeKdf, HpkeKem>(
        &OpModeS::Base,
        client.inner(),
        &info(role, artifact_id, txn, client),
        share.as_bytes(),
        b"",
        rng,
    )
    .map_err(|_| CryptoError::Encryption)?;
    let mut e = [0u8; 32];
    e.copy_from_slice(&enc.to_bytes());
    Ok((e, ct))
}

/// Open a released share with the client's ephemeral secret key.
pub fn open_released_share(
    role: EnvelopeRole,
    client: &KemSecretKey,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    encapped_key: &[u8; 32],
    ciphertext: &[u8],
) -> Result<Share> {
    if ciphertext.len() != SEALED_SHARE_LEN {
        return Err(CryptoError::EnvelopeOpen);
    }
    let enc = <HpkeKem as hpke::Kem>::EncappedKey::from_bytes(encapped_key)
        .map_err(|_| CryptoError::EnvelopeOpen)?;
    let pt = zeroize::Zeroizing::new(
        hpke::single_shot_open::<HpkeAead, HpkeKdf, HpkeKem>(
            &OpModeR::Base,
            client.inner(),
            &enc,
            &info(role, artifact_id, txn, client.public_key()),
            ciphertext,
            b"",
        )
        .map_err(|_| CryptoError::EnvelopeOpen)?,
    );
    let arr: [u8; 32] = pt
        .as_slice()
        .try_into()
        .map_err(|_| CryptoError::EnvelopeOpen)?;
    Ok(Share::from_bytes(arr))
}

/// The OIDC `nonce` value that binds a login to `(e_pk, txn)`.
pub fn nonce_binding(client: &KemPublicKey, txn: &[u8; TXN_LEN]) -> String {
    let mut h = Sha256::new();
    h.update(b"SVX-1 oidc\0");
    h.update(client.to_bytes());
    h.update(txn);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}
