//! Managed Mode key release (see `spec/crypto-profile.md` §12).
//!
//! When the managed service or the recipient key agent releases a share, it
//! re-seals it with HPKE to a fresh one-time key generated by the client for
//! this one request: X-Wing (X25519 + ML-KEM-768) for current clients, so a
//! recorded release can't be decrypted later even with a quantum computer.
//! TLS-terminating intermediaries never see a share, and a captured response
//! is useless without the client's one-time secret key.
//!
//! ```text
//! info = "<suite> release\0" ‖ role ‖ artifact_id ‖ txn ‖ key_id(e_pk)
//! (enc, ct) = HPKE.SealBase(e_pk, info, aad = "", share)
//! ```
//!
//! where `<suite>` is `SVX-1H` for an X-Wing `e_pk` and `SVX-1` for X25519.
//! The client also binds `e_pk` and `txn` into its OIDC login through the
//! `nonce` parameter, so an ID token can only ever be used to release shares
//! to the key pair that requested it:
//!
//! ```text
//! nonce = hex(SHA-256("<suite> oidc\0" ‖ e_pk ‖ txn))
//! ```

use sha2::{Digest, Sha256};
use svx_format::EnvelopeRole;

use crate::SEALED_SHARE_LEN;
use crate::error::{CryptoError, Result};
use crate::keys::{KemPublicKey, KemSecretKey, hpke_ops};
use crate::schedule::Share;
use crate::suite::suite_of_kem;

/// Length of a release transaction identifier.
pub const TXN_LEN: usize = 16;

fn info(
    role: EnvelopeRole,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    client: &KemPublicKey,
) -> Result<Vec<u8>> {
    let mut v = suite_of_kem(client.kind())?.label("release");
    v.push(role.to_byte());
    v.extend_from_slice(artifact_id);
    v.extend_from_slice(txn);
    v.extend_from_slice(&client.key_id());
    Ok(v)
}

/// Re-seal a released share to the client's one-time public key.
pub fn seal_released_share(
    role: EnvelopeRole,
    share: &Share,
    client: &KemPublicKey,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    rng: &mut impl rand_core::CryptoRng,
) -> Result<(Vec<u8>, Vec<u8>)> {
    hpke_ops::seal(
        client,
        &info(role, artifact_id, txn, client)?,
        share.as_bytes(),
        rng,
    )
}

/// Open a released share with the client's one-time secret key.
pub fn open_released_share(
    role: EnvelopeRole,
    client: &KemSecretKey,
    artifact_id: &[u8; 16],
    txn: &[u8; TXN_LEN],
    encapped_key: &[u8],
    ciphertext: &[u8],
) -> Result<Share> {
    if ciphertext.len() != SEALED_SHARE_LEN {
        return Err(CryptoError::EnvelopeOpen);
    }
    let pt = hpke_ops::open(
        client,
        encapped_key,
        &info(role, artifact_id, txn, client.public_key())?,
        ciphertext,
    )?;
    let arr: [u8; 32] = pt
        .as_slice()
        .try_into()
        .map_err(|_| CryptoError::EnvelopeOpen)?;
    Ok(Share::from_bytes(arr))
}

/// The OIDC `nonce` value that binds a login to `(e_pk, txn)`.
pub fn nonce_binding(client: &KemPublicKey, txn: &[u8; TXN_LEN]) -> String {
    // Only KEM keys reach here, so the suite lookup cannot fail.
    let label = suite_of_kem(client.kind())
        .map(|s| s.label("oidc"))
        .unwrap_or_else(|_| b"SVX-1 oidc\0".to_vec());
    let mut h = Sha256::new();
    h.update(&label);
    h.update(client.to_vec());
    h.update(txn);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}
