# Type stubs for the native extension (crates/svx-py). Internal: use the
# `svx` package API instead.
from os import PathLike
from typing import Callable, List, Optional, Tuple

__version__: str

class NativeError(Exception): ...

def inspect(path: str) -> str: ...
def verify(path: str, trust: List[str]) -> str: ...
def generate_signing_key(prefix: str, owner: str) -> str: ...
def generate_kem_key(prefix: str, owner: str) -> str: ...

class NativeClient:
    def __init__(self, config: Optional[str] = None) -> None: ...
    def config_json(self) -> str: ...
    def config_path(self) -> PathLike[str]: ...
    def status(self, path: str) -> str: ...
    def open(
        self,
        path: str,
        output_dir: Optional[str],
        overwrite: bool,
        dev_user: Optional[str],
        browser: bool,
        on_step: Optional[Callable[[str, Optional[str]], None]],
    ) -> str: ...
    def open_bytes(
        self,
        path: str,
        dev_user: Optional[str],
        browser: bool,
        on_step: Optional[Callable[[str, Optional[str]], None]],
    ) -> Tuple[str, bytes]: ...
    def pack(
        self,
        input: str,
        output: Optional[str],
        recipient: str,
        policy: str,
        signing_key: str,
        expires_at: Optional[int],
        classification: Optional[str],
        description: Optional[str],
        name: Optional[str],
        overwrite: bool,
        register: bool,
    ) -> str: ...
    def login(self, dev_user: Optional[str], browser: bool) -> str: ...
    def logout(self) -> bool: ...
    def whoami(self) -> str: ...
    def revoke(self, target: str) -> str: ...
    def policies(self) -> str: ...
    def set_policy(self, name: str, policy_json: str) -> str: ...
    def audit(self, limit: int) -> str: ...
    def org_record(self, org: str) -> str: ...
